spring:
  application:
    name: proj_api_clube_livro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clube-livro-db?createDatabaseIfNotExist=true
    password: 38441381
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

